name: "PHPStan"

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: "7.4"
            phpunit-version-constraint: "^7.5"
          - php-version: "8.3"
            phpunit-version-constraint: "^9.6"

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: highest

      - name: Run PHPStan
        run: |
          composer require --dev phpunit/phpunit:"${{ matrix.phpunit-version-constraint }}" --with-all-dependencies -n
          vendor/bin/phpstan analyse
